#include "FactoryShapeMaterials.h"

#include "FactorySimTypes.h"
#include "Materials/MaterialInterface.h"
#include "UObject/Package.h"

#if WITH_EDITOR
#include "AssetRegistry/AssetRegistryModule.h"
#include "FileHelpers.h"
#include "Materials/MaterialInstanceConstant.h"
#endif

namespace FactoryShapeMaterials
{
	UMaterialInterface* Load(const TCHAR* Name)
	{
		const FString Path = FString::Printf(TEXT("%s/%s.%s"), Folder, Name, Name);
		return LoadObject<UMaterialInterface>(nullptr, *Path);
	}

#if WITH_EDITOR
	namespace
	{
		struct FSpec
		{
			const TCHAR* Name;
			FLinearColor Colour;
		};

		const FSpec Specs[] = {
			// Deliberately loud. A carrier is the thing you follow to read the
			// line at a glance, and the first one was near-black on a near-black
			// belt, which made a running line look like a stopped one.
			{ Carrier,   FLinearColor(0.90f, 0.35f, 0.02f) },  // safety orange
			{ Housing,   FLinearColor(0.55f, 0.57f, 0.60f) },  // cast aluminium
			{ Connector, FLinearColor(0.02f, 0.02f, 0.02f) },  // black plastic
			{ Board,     FLinearColor(0.02f, 0.30f, 0.10f) },  // green laminate
			{ Lid,       FLinearColor(0.70f, 0.72f, 0.75f) },
			{ Carton,    FLinearColor(0.45f, 0.30f, 0.15f) },  // cardboard
			{ LampPass,  FLinearColor(0.05f, 0.90f, 0.15f) },
			{ LampFail,  FLinearColor(0.90f, 0.05f, 0.05f) },
			{ GridMinor, FLinearColor(0.30f, 0.32f, 0.35f) },
			{ GridMajor, FLinearColor(0.10f, 0.45f, 0.70f) },
			{ Belt,      FLinearColor(0.08f, 0.08f, 0.09f) },
		};
	}

	int32 EnsureAll()
	{
		UMaterialInterface* Parent = LoadObject<UMaterialInterface>(nullptr, ParentMaterial);
		if (Parent == nullptr)
		{
			UE_LOG(LogFactorySim, Warning,
				TEXT("Shape material parent '%s' is missing; level geometry will be untinted"),
				ParentMaterial);
			return 0;
		}

		TArray<UPackage*> ToSave;
		int32 Created = 0;
		int32 Updated = 0;

		for (const FSpec& Spec : Specs)
		{
			// Reconcile rather than skip. These colours are defined in code, so an
			// asset generated by an earlier run must be brought back into line
			// with it; skipping anything that already exists meant editing a
			// colour here silently did nothing.
			if (UMaterialInterface* Existing = Load(Spec.Name))
			{
				UMaterialInstanceConstant* Constant = Cast<UMaterialInstanceConstant>(Existing);
				if (Constant == nullptr)
				{
					continue;
				}

				FLinearColor Current;
				const bool bHasValue = Constant->GetVectorParameterValue(
					FMaterialParameterInfo(TEXT("Color")), Current);
				if (bHasValue && Current.Equals(Spec.Colour))
				{
					continue;
				}

				Constant->SetVectorParameterValueEditorOnly(
					FMaterialParameterInfo(TEXT("Color")), Spec.Colour);
				Constant->PostEditChange();
				Constant->MarkPackageDirty();
				ToSave.Add(Constant->GetOutermost());
				++Updated;
				continue;
			}

			const FString PackageName = FString::Printf(TEXT("%s/%s"), Folder, Spec.Name);
			UPackage* Package = CreatePackage(*PackageName);
			if (Package == nullptr)
			{
				continue;
			}

			UMaterialInstanceConstant* Instance = NewObject<UMaterialInstanceConstant>(
				Package, FName(Spec.Name), RF_Public | RF_Standalone);
			if (Instance == nullptr)
			{
				continue;
			}

			Instance->SetParentEditorOnly(Parent);
			Instance->SetVectorParameterValueEditorOnly(
				FMaterialParameterInfo(TEXT("Color")), Spec.Colour);
			Instance->PostEditChange();

			FAssetRegistryModule::AssetCreated(Instance);
			Package->MarkPackageDirty();
			ToSave.Add(Package);
			++Created;
		}

		if (ToSave.Num() > 0)
		{
			UEditorLoadingAndSavingUtils::SavePackages(ToSave, /*bOnlyDirty*/ false);
			UE_LOG(LogFactorySim, Display,
				TEXT("Shape materials: %d created, %d recoloured"), Created, Updated);
		}
		return Created + Updated;
	}
#endif
}
